### ISSUE TITLE
Android 10 대응 TODO List

### ISSUE THREAD

**Issue by 5seunghoon** [5seunghoon/PreviewMaker#8]
- [x] targetSdk 변경 및 AndriodX로 마이그레이션 : https://github.com/5seunghoon/PreviewMaker/pull/6

- [x] 멀티이미지 불러올 수 있게 변경 : https://github.com/5seunghoon/PreviewMaker/pull/7

- [x] 멀티이미지를 Rx하게 불러오게 변경 : https://github.com/5seunghoon/PreviewMaker/pull/7

- [x] 이미지를 파일로 불러와서 캔버스에 그리는 과정을 Rx로 변경 : https://github.com/5seunghoon/PreviewMaker/pull/14

- [x] 블러링 과정을 Rx로 변경 : https://github.com/5seunghoon/PreviewMaker/pull/15

- [x] 안드로이드10 미만에서도 썸네일은 비트맵 활용 : https://github.com/5seunghoon/PreviewMaker/pull/12

- [x] .nomedia 적용 : https://github.com/5seunghoon/PreviewMaker/pull/20

- [x] 상태바 색깔 변경 : https://github.com/5seunghoon/PreviewMaker/pull/18

- [x] 그 외 자주 일어나는 크래쉬 해결 
    1. https://github.com/5seunghoon/PreviewMaker/pull/16
    2. https://github.com/5seunghoon/PreviewMaker/pull/17

#### 자주 일어나는 크래쉬 
1. FileNotFoundException - 프리뷰를 캔버스에 그릴 때 파일을 찾을 수 없는 경우가 있는 듯 함
```
Caused by: java.io.FileNotFoundException: 
  at java.io.FileInputStream.open0 (Native Method)
  at java.io.FileInputStream.open (FileInputStream.java:231)
  at java.io.FileInputStream.<init> (FileInputStream.java:165)
  at java.io.FileInputStream.<init> (FileInputStream.java:112)
  at android.media.ExifInterface.<init> (ExifInterface.java:1335)
  at com.tistory.deque.previewmaker.kotlin.model.Preview.getBitmap (Preview.kt:59)
  at com.tistory.deque.previewmaker.kotlin.previewedit.KtPreviewEditViewModel$LoadingPreviewToCanvas.doInBackground (KtPreviewEditViewModel.kt:332)
  at com.tistory.deque.previewmaker.kotlin.previewedit.KtPreviewEditViewModel$LoadingPreviewToCanvas.doInBackground (KtPreviewEditViewModel.kt:329)
  at android.os.AsyncTask$2.call (AsyncTask.java:333)
  at java.util.concurrent.FutureTask.run (FutureTask.java:266)
```

2. IllegalStateException - setPixels에 음수가 들어가는 것으로 예상 
```
java.lang.IllegalStateException: 
  at android.graphics.Bitmap.setPixels (Bitmap.java:2274)
  at com.tistory.deque.previewmaker.kotlin.manager.BlurManager.doFastBlur (BlurManager.kt:443)
  at com.tistory.deque.previewmaker.kotlin.manager.PreviewBitmapManager.blurBitmap (PreviewBitmapManager.kt:189)
  at com.tistory.deque.previewmaker.kotlin.previewedit.KtPreviewEditViewModel$MakeBlurAsyncTask.doInBackground (KtPreviewEditViewModel.kt:352)
  at com.tistory.deque.previewmaker.kotlin.previewedit.KtPreviewEditViewModel$MakeBlurAsyncTask.doInBackground (KtPreviewEditViewModel.kt:349)
  at android.os.AsyncTask$2.call (AsyncTask.java:333)
  at java.util.concurrent.FutureTask.run (FutureTask.java:266)
```

**Comment by 5seunghoon** [comment]
Approve all todo list
